"""Initial migration

Revision ID: a8f06bcd3d65
Revises: 
Create Date: 2026-10-07 19:53:30.989123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f06bcd3d65'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cheese_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=499), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_cheese_type_id'), 'cheese_type', ['id'], unique=False)
    op.create_table('cheese',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Double(), nullable=False),
    sa.Column('packaging_type', sa.Enum('IN_PACKAGE', 'WEIGHT', name='packagingtype'), nullable=False),
    sa.Column('cheese_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cheese_type_id'], ['cheese_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_cheese_id'), 'cheese', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cheese_id'), table_name='cheese')
    op.drop_table('cheese')
    op.drop_index(op.f('ix_cheese_type_id'), table_name='cheese_type')
    op.drop_table('cheese_type')
    # ### end Alembic commands ###
